### PR TITLE
changing upstream DNS servers to Cloudflare and OpenDNS

### PR DESCRIPTION
**Pull request by sfoerster**
Cloudflare and OpenDNS are both speedy and privacy-oriented

### CODE REVIEW

**Comment by Woodham** [comment]
+1 I think this would be useful, but cloudflare actually has a secondary DNS server at `1.0.0.1` - see here https://developers.cloudflare.com/1.1.1.1/setting-up-1.1.1.1/

**Comment by sfoerster** [comment]
The upstream DNS servers have been set to the Cloudflare primary (1.1.1.1) and secondary (1.0.0.1) servers.

**Comment by CorbanR** [comment]
Nice I agree, and I like the changes.

**Comment by CorbanR** [comment]
At some point it would be nice to get DoH, and DoT enabled.

**Comment by CorbanR** [comment]
@sfoerster thanks!

**Pull request merged**
