### PR TITLE
Disabled pub key existence checking when provisioning existing server…

### PR DESCRIPTION
**Pull request by Lexy2**
… and localhost.

Done by adding a parameter to ~/.streisand/site.yml which is checked at validation and pub key checking is skipped if parameter is defined.

### CODE REVIEW

**Comment by Lexy2** [comment]
Fix for #1295

**Comment by Lexy2** [comment]
Hi @cpu , 

Thank you very much for the comments. Yes, your approach looks prettier. Let me amend the PR.

Regards, Lexy

**Comment by Lexy2** [comment]
Hi @cpu,

I have pushed the amendments here. Travis fails because the no_check_pub_key (renamed to streisand_new_server_provisioning) is not define per se in any vars and is only passed in ./streisand script.

Would you like me to test if the var is defined or add a default value to default inventory?

Thanks.

Lexy

**Comment by cpu** [comment]
Hi @Lexy2,

Thanks for pushing those changes. It looks great :+1:  I like the new var name.

> Would you like me to test if the var is defined or add a default value to default inventory?

Historically I think we've handled this by adding a default value but its a bit messy and needs to be done in a couple spots. Let's try the alternative you suggest and consider `no_check_pub_key` enabled if its defined at all. I think that's reasonable for this case .

**Comment by Lexy2** [comment]
Thanks, I suppose when you said
> consider no_check_pub_key enabled if its defined at all
you meant
consider `streisand_new_server_provisioning` enabled if undefined.

**Comment by cpu** [comment]
> you meant consider streisand_new_server_provisioning enabled if undefined.

@Lexy2 Oops, yes :-) Sorry to confuse things. You got it.

**Comment by Lexy2** [comment]
Hi @cpu ,

Please kindly review the proposed changes.
I tried your variant of testing if `streisand_new_server_provisioning` undefined but I think setting a default value is a better option:

- code is prettier
- the change is still local to validation task
- easier overridden since defaults have the lowest priority

Thank you!

Regards, Lexy

**Comment by cpu** [comment]
> Please kindly review the proposed changes.

Hi @Lexy2 - great! Thank you. I'll try to take a look at this PR this evening after work.

> I tried your variant of testing if streisand_new_server_provisioning undefined but I think setting a default value is a better option

Ok! I'm not opposed to handling it this way :+1:

**Comment by Lexy2** [comment]
Thanks for guiding me through my first one, @cpu !

Appreciate your feedback.

**Pull request merged**
