### PR TITLE
Use ec2_ami_facts instead of deprecated ec2_ami_find. fixes #1229

### LINKED ISSUE #1229: EC2 Provisioning: "The 'ec2_ami_find' module has been deprecated. Use 'ec2_ami_facts' instead."
### Expected behavior:

Provisioning an EC2 instance with Streisand produces no warnings.

### Actual Behavior:

Streisand produces the output:
```
TASK [genesis-amazon : Determine which AMI to use] *************************************************************************************************************************************************************
[DEPRECATION WARNING]: The 'ec2_ami_find' module has been deprecated. Use 'ec2_ami_facts' instead.. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
```

### Steps to Reproduce:
1. `./streisand`
2. Choose Amazon provisioning
3. Wait

### PR DESCRIPTION
**Pull request by matalo33**
fixes #1229

### CODE REVIEW

**Review by lifeart — APPROVED** [review]

**Comment by alimakki** [comment]
I believe the root cause of the issue is that CI builds on Ansible v2.4 where as the Amazon module was modified in Ansible v2.5, hence causing this error.

**Review by alimakki — APPROVED** [review]
Tested w/ Ansible 2.5 on AWS, no warnings. LGTM :+1:

**Comment by cpu** [comment]
@matalo33 Thanks for the PR! :clinking_glasses: 

> I believe the root cause of the issue is that CI builds on Ansible v2.4 where as the Amazon module was modified in Ansible v2.5, hence causing this error.

I'm open to moving to requiring 2.5. I've been using it myself for Streisand dev work for a few weeks without issue.

@matalo33 Do you want to update the required Ansible version & the CI installed Ansible version as part of this PR to fix the test failure?

You can do the first by changing the `REQUIRED_ANSIBLE_VERSION` var: https://github.com/StreisandEffect/streisand/blob/7f414cc7227be9beb9d29a27ecebd23bab78d580/util/ansible_check.sh#L9

And the second by changing the `.travis.yml` install cmd: https://github.com/StreisandEffect/streisand/blob/7f414cc7227be9beb9d29a27ecebd23bab78d580/.travis.yml#L27

thanks!

**Review by cpu — CHANGES_REQUESTED** [review]
Needs the Ansible version in CI/reqs bumped. Thanks!

**Comment by alimakki** [comment]
@cpu I’ve tried bumping it but I keep getting ssh private key not found after stating it

**Comment by nopdotcom** [comment]
While you're thinking about this, I should force the Ansible rev in `requirements.txt` to 2.5?

**Comment by cpu** [comment]
> @cpu I’ve tried bumping it but I keep getting ssh private key not found after stating it

@alimakki Blech :-( Ok. Sounds like this PR will be blocked until we can figure out why 2.5 breaks CI. Can you file an issue for that with the error output and I'll link it to this?

**Comment by alimakki** [comment]
Opened issue #1276

**Comment by alimakki** [comment]
@cpu tested on AWS with no issues

**Comment by cpu** [comment]
@alimakki Great thanks! I think this is ready to merge.

**Review by cpu — APPROVED** [review]
Thanks @matalo33 - I appreciate the PR! Apologies on having this one sit for a while. We'll try to get future contributions merged faster :-)

**Pull request merged**
