### PR TITLE
Specify GRUB2 kernel by default when deploying via Linode

### PR DESCRIPTION
**Pull request by rmcintosh**
This ties to https://github.com/ansible/ansible/pull/23100 which was submitted to help ease the issues described in https://github.com/jlund/streisand/issues/500

The change makes the deployed instance use the GRUB2 Linode kernel option which now allows use of the distribution's supplied kernel, rather than the hypervisor's kernel.

I'm not intimately familiar with streisand so If I've missed the mark somewhere, please let me know.

### CODE REVIEW

**Comment by jlund** [comment]
This is fantastic! Thanks for making this happen.

We will need to wait until the `kernel_id` argument is in a released version of Ansible before we can merge this PR, but it looks like that will be happening soon. At that point we can change the required Ansible version [here](https://github.com/jlund/streisand/blob/master/streisand#L15) and :shipit:

**Comment by zx2c4** [comment]
Ansible 2.3 was released -- https://github.com/ansible/ansible/releases/tag/v2.3.0.0-1 -- which means this can now be merged. I'd recommend, though, updating the pull request commit to make @jlund's suggested change with pumping the required Ansible version.

**Comment by cpu** [comment]
@zx2c4 I might be confused, but it looked like the relevant commit was [in the 425 commits to devel after the tag](https://github.com/ansible/ansible/compare/v2.3.0.0-1...devel). Did you find release notes for v.2.3.0.0-1 that mention the required commit?

**Comment by rmcintosh** [comment]
For anyone not following along on both issues: Ansible change won't see the
light of day until the 2.4 release, I believe.

**Comment by cpu** [comment]
When this is merged we should also revert fc73677, the workaround from #609

**Comment by rmcintosh** [comment]
@jlund for this, it seems like we should we just hardcode the kernelid as in https://github.com/jlund/streisand/pull/613, yeah?

**Comment by zx2c4** [comment]
I think you have the right idea here. I've submitted a PR -- https://github.com/jlund/streisand/pull/623 -- for making the distro id more like how you do it in this PR.

**Comment by rmcintosh** [comment]
fair enough, thanks @zx2c4! I'll match up after it's merged

**Comment by cpu** [comment]
I think the Ansible release we were waiting for on this PR is out. Might be time to knock the cobwebs off and see if we can land this and retire a monkey patch :-)

**Comment by rmcintosh** [comment]
nice - I will do that

thanks for the heads up!

**Comment by rmcintosh** [comment]
the conflicts here are annoying to fix so I'm just going to re-PR this since it is not a large change

**Comment by cpu** [comment]
Thanks for sticking with this one @rmcintosh :-) Nice to see a ticket from April 4th marked closed! :tada: :tada: :tada:

**Comment by rmcintosh** [comment]
Happy to have helped! ❤️

**Pull request closed without merging**
