### PR TITLE
Add OpenConnect GUI instructions for MacOS

### PR DESCRIPTION
**Pull request by GauthierPLM**
A mirror of OpenConnect GUI for Mac should be added.
Also, I kept the CLI instructions as they can be relevant to actual users or people willing to use CLI instead of GUI.
Finally, not like Windows, Mac OS doesn't need any special configuration for DNS (from what I saw on my system) so I didn't kept them.

### CODE REVIEW

**Comment by alimakki** [comment]
@GauthierPLM out of curiosity, which version of OpenConnect GUI did you use? My last attempt was with 1.5.1 on macOS Sierra and was more or less unstable (crashes on connection attempt).

**Comment by GauthierPLM** [comment]
It's also 1.5.1, on High Sierra. It worked well for me until now (used it for few days in China).

**Comment by alimakki** [comment]
We have the mirroring code for the OpenConnect GUI already there, it's just been commented out. I'll re-visit it once I'm back in Montreal.

**Comment by cpu** [comment]
> We have the mirroring code for the OpenConnect GUI already there, it's just been commented out. I'll re-visit it once I'm back in Montreal.

Aha. I won't merge this until that's ready.

@GauthierPLM Do you want to uncomment the required mirroring as part of this PR so it can be merged before @alimakki returns? You only have to uncomment these lines: https://github.com/StreisandEffect/streisand/blob/77611d3e04a1d09e0f39f206af61c4b150255a09/playbooks/roles/openconnect/vars/mirror.yml#L24-L32

**Comment by alimakki** [comment]
This part will need to be uncommented as well:

https://github.com/StreisandEffect/streisand/blob/77611d3e04a1d09e0f39f206af61c4b150255a09/playbooks/roles/openconnect/vars/mirror.yml#L37

Additionally, the mirror and mirror-fr templates need to be updated as well so users are able to download the dmg.

**Comment by cpu** [comment]
@alimakki Good catch! Thanks for adding those places too.

**Comment by cpu** [comment]
>  @GauthierPLM Do you want to uncomment the required mirroring as part of this PR so it can be merged before @alimakki returns? You only have to uncomment these lines:

@alimakki Beat you to it with #1235 :rabbit2: :racehorse: 

I've merged master back into this branch. Once CI passes it will be ready to merge.

**Comment by GauthierPLM** [comment]
Sorry, I was far for few days. Thanks for merging and thank you @alimakki for uncommenting necessary stuff :)

**Pull request merged**
