### PR TITLE
Update to Ansible 2.4 syntax

### PR DESCRIPTION
**Pull request by wzyboy**
This patch updates `include` syntax to `import_tasks` `include_tasks` `import_playbook`, and raises the required version of Ansible to 2.4.

I have tested this on a fresh EC2 instance, all went well.

Ref: https://github.com/StreisandEffect/streisand/issues/994

### CODE REVIEW

**Comment by wzyboy** [comment]
Hmm, I had a full run of the playbook on a fresh EC2 instance and no problems were found. The CI still uses Ansible 2.3 so it fails the version check.

**Comment by wzyboy** [comment]
Ansible version in CI is now updated to 2.4 as well, along with the `roles_path` fix. The CI is passing now.

**Comment by cpu** [comment]
Thanks for taking this on @wzyboy - I will review shortly.

**Comment by wzyboy** [comment]
Resolved conflicts and rebased.

**Comment by cpu** [comment]
@wzyboy Perfect! Thanks for the quick update. I'll merge this once the CI completes.

**Pull request merged**
