### PR TITLE
Add Linode API v4 support

### PR DESCRIPTION
**Pull request by patthiel**
* Streisand uses the older `linode` ansible module, which uses the deprecated Linode API v3. Recently, Ansible v2.8.0 was released with a new `linode_v4` [module](https://docs.ansible.com/ansible/latest/modules/linode_v4_module.html). This PR updates the linode playbooks to use the new module.
* Since this module relies on Ansible 2.8.0 I had to upgrade the minimum Ansible version requirements to that version. 
* I've tested the Linode provider with these changes, but i have not tested if the Ansible 2.8.0 upgrade breaks any of the other providers (any help with that would be greatly appreciated!).

### CODE REVIEW

**Comment by CorbanR** [comment]
I've spun up a few Streisand servers now using ansible 2.8 and so far so good(albeit a bunch of deprecation warnings..) Still need to try a few other providers.

**Comment by mdmdj** [comment]
Does this resolve issue #1543 ?

**Comment by JonathanLehner** [comment]
would be good to add the ansible version to ./util/venv-dependencies.sh

**Comment by JonathanLehner** [comment]
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Authentication failed"}
I got this error on your fork

**Comment by patthiel** [comment]
> would be good to add the ansible version to ./util/venv-dependencies.sh

Are you suggesting adding a check for a globally installed ansible version 2.8 and if it's not installed, adding it to the virtual environment?

**Comment by patthiel** [comment]
@mdmdj 
> Does this resolve issue #1543 ? 

yes, it does

**Comment by patthiel** [comment]
@JonathanLehner
> fatal: [localhost]: FAILED! => {"changed": false, "msg": "Authentication failed"}
I got this error on your fork

Hmm, i just re-ran everything on my end and it worked. Did you get your linode api token from here: https://cloud.linode.com/profile/tokens ?

Tokens from https://manager.linode.com are not compatible, unfortunately (v4 api is breaking). 

I would do the following to make sure this fork works as intended:

1. Checkout and pull down the latest of this fork & branch (I've just merged latest master into it)
2. Remove your existing virtual environment
3. `./util/venv-dependencies.sh ./venv` (this will install the latest ansible and the linode package in `requirements.txt`)
4. `source venv/bin/activate`
4. `./streisand` (this will check for ansible v2.8 installed)
5. Choose Linode, and use your token from https://cloud.linode.com/profile/tokens

I went with the defaults for all the prompts, but I think you ran into your authentication issue before reaching any of the additional installation prompts. Please let me know if you're still running into your authentication issue, I'm happy to help you debug!

**Comment by patthiel** [comment]
@JonathanLehner did you have a chance to pull latest of this branch and re-test?

**Comment by chopraaa** [comment]
Can you add support for Mumbai? (if the API supports it)

**Comment by patthiel** [comment]
Good call @chopraaa , added!  

If you have trouble running this branch or testing this PR, i have encountered this issue that others have reported related to GPG key import https://github.com/StreisandEffect/streisand/issues/1597

**Comment by patthiel** [comment]
@CorbanR @alimakki I can make a separate PR for upgrading to Ansible `v2.8`. It probably makes the most sense to decouple that change from this PR.

**Comment by alimakki** [comment]
> 
> 
> @CorbanR @alimakki I can make a separate PR for upgrading to Ansible `v2.8`. It probably makes the most sense to decouple that change from this PR.

No issues from my side :)

**Comment by CorbanR** [comment]
Sorry for the late response, I haven't had a ton of time lately, but I should be able to review / run at least a couple tests on this tomorrow

**Comment by CorbanR** [comment]
@patthiel Thank you for the pull request, and thank you for your patience.

**Pull request merged**
