### PR TITLE
Feature: DNS-over-HTTPS option implemented with cloudflared (default: yes)

### PR DESCRIPTION
**Pull request by sfoerster**
Adding role: cloudflared (depends on dnsmasq [declared in meta/main.yml])

Activated with "streisand_cloudflared_enabled" either directly set in ~/.streisand/site.yml or through prompt triggered by customize.yml.

Modifies dnsmasq.conf with single "server" line redirecting DNS to the localhost proxy-dns {{ cloudflared_port }}

The upstream DNS servers remain 1.1.1.1 and 1.0.0.1 (Cloudflare) but can be changed in playbooks/roles/cloudflared/default/main.yml

### CODE REVIEW

**Comment by sfoerster** [comment]
Given these kinds of stories coming out, it appears that DNS-over-HTTPS achieves what it's supposed to and is critical to individuals vulnerable to censorship and worse

[UK ISP group names mozilla internet villain for supporting DNS-over-HTTPS](https://www.zdnet.com/article/uk-isp-group-names-mozilla-internet-villain-for-supporting-dns-over-https/)

**Comment by chopraaa** [comment]
Is there a reason we're not going with `dnscrypt-proxy`? It has a ton of features and supports filtering out of the box. There's no reason to lock in with Cloudflare.

This should also be a default setting IMHO, and we can have preconfigured filters in Streisand that block malware/malicious advertisements.

**Comment by sfoerster** [comment]
Agreed that `dnscrypt-proxy` support would be a nice-to-have thing to add in the future. As far as filtering malware/ads go we could add a pihole role. This is actually the configuration my family is using: streisand server w/ Wireguard+DoH and manually added pihole afterward. It's been working great for several weeks now but I haven't bothered to elegantly integrate the streisand and pihole web interfaces yet.

**Comment by rdbox** [comment]
> Agreed that `dnscrypt-proxy` support would be a nice-to-have thing to add in the future. As far as filtering malware/ads go we could add a pihole role. This is actually the configuration my family is using: streisand server w/ Wireguard+DoH and manually added pihole afterward. It's been working great for several weeks now but I haven't bothered to elegantly integrate the streisand and pihole web interfaces yet.

I still do not understand how I enable DNS-over-HTTPS
I ask you to write action points in more detail.

**Comment by sfoerster** [comment]
@rdbox this is still a pull request not yet merged into the main streisand repo so you'll need to checkout the forked branch

For example:
`git clone https://github.com/sfoerster/streisand -b cloudflared`

Then you just run streisand normally and enable DNS-over-HTTPS will appear as a customizing option:

`cd streisand`
`./util/venv-dependencies ./venv`
`source ./venv/bin/activate`
`./streisand`

After selecting a cloud provider you will go through the customization options and the last one is the DNS-over-HTTPS option:

`Enter the path to your SSH private key, or press enter for default  [~/.ssh/id_rsa]: 
How many VPN client profiles should be generated per-service (min: 1 max: 20)? Press enter for default  [5]: 
Enable OpenConnect? Press enter for default  [yes]: 
Enable OpenVPN? Press enter for default  [yes]: 
Enable stunnel service (only allowed for OpenVPN)? Press enter for default  [yes]: 
Enable Shadowsocks? Press enter for default  [yes]: 
Enable SSH Forward User? (Note: A SOCKS proxy only user will be added, no shell). Press enter for default  [yes]: 
Enable sshuttle? (Note: A full shell access user will be added) Press enter for default  [no]: 
Enable tinyproxy? Press enter for default  [yes]: 
Enable Tor? Press enter for default  [no]: 
Enable WireGuard? Press enter for default  [yes]: 
**Enable DNS-over-HTTPS (cloudflared)? Press enter for default  [yes]:**`

**Comment by alimakki** [comment]
LGTM 👍

**Pull request merged**
