### PR TITLE
Fix "No valid certificates available for authentication" error for iOS OpenConnect

### LINKED ISSUE #1396: AnyConnect iOS cannot connect to VPN
### Expected behavior:

After the creation of a new server and the configuration of AnyConnect, the app should be able to connect to the VPN.
The app is supposed to ask an username and a password for first connection.

### Actual Behavior:

When following the instructions to setup AnyConnect on iOS, everything goes well until connection which is always a failure when connecting.

No credentials were required when setting up the certificate nor for the first connection that failed.

### Steps to Reproduce:
1. Install a fresh Streisand server on Google Cloud.
2. Follow the instructions to setup AnyConnect
3. Try to connect. A message saying that an error occurred while trying to connect appears.

I attached a domain name to the server and Streisand configured a Let's Encrypt certificate. Connection to the server works well.
This also happens on an instance I setup in February which I didn't touched since.

The version of the AnyConnect app is 4.6.01099

### PR DESCRIPTION
**Pull request by alimakki**
- .mobileconfig re-generated from Apple Configurator 2 (`DeviceUniqueIdentifier` key/value from `VedorConfig` and `ProviderType` `packet-tunnel`  setting now removed)
 - uppercase UUIDs

Tested on DO instance successfully. Thanks @MRizkBV for the heads up.

Resolves #1396

### CODE REVIEW

**Comment by ammaristotle** [comment]
@alimakki I tested your fix on GCP, can confirm it's working.

**Comment by nopdotcom** [comment]
LGTM!

**Comment by alimakki** [comment]
Thanks for the review @nopdotcom

**Comment by GauthierPLM** [comment]
Will I need to redeploy my VPNs to fix this?
Is there anyway to update Streisand install without regenerating all the certificates?

**Comment by alimakki** [comment]
You should be able to edit the existing .mobileconfigs.

Try removing the following settings from the mobileconfig and re-importing them into your device:
```
<key>ProviderType</key>
<string>packet-tunnel</string>
```
```
<key>DeviceUniqueIdentifier</key>
<string>{DeviceUid}</string>
```

**Pull request merged**
