### PR TITLE
Updated Wording for OpenVPN - Ubuntu for Ubuntu 17.10 (Fixed)

### PR DESCRIPTION
**Pull request by Frichetten**
This may be a little nit-picky but I noticed that some of the wording is off for installing OpenVPN on Ubuntu. I think some changes were made in 17.10 and now things are laid out a little differently.

I made 2 changes to the instructions. First, Instead of telling the user to check a box (it no longer exists), I mentioned that they should view a particular section (so they can update that information).

Second, there is no 'Save' button anymore, it is now referred to as 'Add'. I've linked some screenshots below.

[No Check Box](http://frichetten.com/images/z-9.png)
[No Save Button](http://frichetten.com/images/z-10.png)

If this looks like a repeat, it is. This was originally Pull Request #1149 . I wanted to make a quick fix so I did it on my Master branch. After that, I found something different to work on. To save the headache, I just closed it and did it the proper way :P

### CODE REVIEW

**Comment by alimakki** [comment]
@Frichetten you're probably right, if I remember correctly I made some changes based off of Ubuntu 16.04.

**Comment by cpu** [comment]
Thanks again @Frichetten :trophy:

**Comment by Frichetten** [comment]
@alimakki Does the documentation target a specific version of Mac OS or Linux? I'm sure there a little variances here and there that may make updatings the documentation tedious, but then again it's probably not radically different :P

**Comment by alimakki** [comment]
@Frichetten not that I'm aware of, but I take into account the Serrias for mac, though I'd defer to the better judgment of others when it comes to Linux :)

**Pull request merged**
